version: '3.8'

services: 
  api:
    container_name: api
    build:
      context: ./api
    ports: 
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - my-network
    
  web:
    container_name: web
    build: 
      context: ./web
    ports: 
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web
    networks:
      - my-network

networks:
  my-network:
    driver: bridge